version: "3.8"

services:
  agent:
    image: postgres
    build: .
    environment:
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
