version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=test
    ports:
      - "5432:5432"
    volumes:
    - ./create.sql:/docker-entrypoint-initdb.d/create.sql
  test:
    image: test
    build: .
    environment:
      - PGPASSWORD=test
      - PGHOST=db
    entrypoint: ["/usr/local/go/bin/go", "test"]
